; INICIALIZAMOS LAS VARIABLES
INICIO.PAL = $0600
	org INICIO.PAL
DETECTA.PAL
	LDA VCOUNT
	CMP #100
	BNE DETECTA.PAL ;BUSCA SCANLINE 100
	LDA #2
	STA CDTMV3  ; 2 BARRIDOS DE PANTALLA
	LDA #$00
	STA CDTMV3+1 ;SOLO 2 BARRIDOS
DETECTA.PAL.LOOP
	LDA VCOUNT
	CMP #135
	BEQ DETECTA.PAL.SI.PAL
	LDA CDTMV3  ; 2 BARRIDOS?
	BNE DETECTA.PAL.LOOP ; NO!
	BEQ DETECTA.PAL.NTSC ;ES NTSC!
DETECTA.PAL.SI.PAL
	LDA #$01
DETECTA.PAL.NTSC
	STA PALNTS
	RTS
